---
pages:
- thank-you.md
- recycling-tandc.md
- recycling.md
- partners.md
- mobile-for-a-meal.md
- locator-map.md
- education.md
- contact.md
- about.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: fimage
  label: Fimage
  type: text
  hidden: false
  default: ''
- name: url
  label: Url
  type: text
  hidden: false
  default: ''
- name: includemaplocator
  label: Includemaplocator
  type: boolean
  hidden: false
  default: ''
- name: blurbl1
  label: Blurbl1
  type: text
  hidden: false
  default: ''
- name: blurbl2
  label: Blurbl2
  type: text
  hidden: false
  default: ''
- name: blurbl3
  label: Blurbl3
  type: text
  hidden: false
  default: ''
- name: section1t
  label: Section1t
  type: text
  hidden: false
  default: ''
- name: section1c
  label: Section1c
  type: textarea
  hidden: false
  default: ''
- name: section2t
  label: Section2t
  type: text
  hidden: false
  default: ''
- name: section2l
  label: Section2l
  type: text
  hidden: false
  default: ''
- name: section2c
  label: Section2c
  type: textarea
  hidden: false
  default: ''
- name: section3t
  label: Section3t
  type: text
  hidden: false
  default: ''
- name: section3l
  label: Section3l
  type: text
  hidden: false
  default: ''
- name: section3c
  label: Section3c
  type: textarea
  hidden: false
  default: ''
- name: section4t
  label: Section4t
  type: text
  hidden: false
  default: ''
- name: section4l
  label: Section4l
  type: text
  hidden: false
  default: ''
- name: section4c
  label: Section4c
  type: text
  hidden: false
  default: ''
- name: section5t
  label: Section5t
  type: text
  hidden: false
  default: ''
- name: section5l
  label: Section5l
  type: text
  hidden: false
  default: ''
- name: section5c
  label: Section5c
  type: text
  hidden: false
  default: ''
- name: section6t
  label: Section6t
  type: text
  hidden: false
  default: ''
- name: section6l
  label: Section6l
  type: text
  hidden: false
  default: ''
- name: section6c
  label: Section6c
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
